-- Bu SQL'i Supabase Dashboard > SQL Editor içine yapıştırıp "Run" ile çalıştır.
-- Tabloyu Table Editor üzerinden zaten oluşturduysan, sadece eksik kısımları çalıştırman yeterli.

-- Tablo (Table Editor'dan oluşturmadıysan burada da oluşturabilirsin):
create table if not exists geri_bildirimler (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  lat float8 not null,
  lon float8 not null,
  durum text not null check (durum in ('carsaf', 'iyi', 'hafif', 'fazla', 'tehlikeli')),
  not_metni text,
  faydali_sayisi int not null default 0,
  kullanici_adi text,
  konum_metni text   -- "Mimar Sinan Mah., Atakum, Samsun" formatında, Nominatim'den otomatik doldurulur
);

-- Eğer tabloyu daha önce oluşturduysan ve faydali_sayisi/kullanici_adi kolonu yoksa, sadece bunu çalıştır:
alter table geri_bildirimler add column if not exists faydali_sayisi int not null default 0;
alter table geri_bildirimler add column if not exists kullanici_adi text;
-- YENİ: yorumun yapıldığı konumu metin olarak saklar. Eski yorumlarda boş kalır, sorun olmaz.
alter table geri_bildirimler add column if not exists konum_metni text;

-- Sistem 3 kademeden (sakin/dikkatli/riskli) 5 kademeye (carsaf/iyi/hafif/fazla/tehlikeli)
-- geçtiği için, eski "durum" kısıtını kaldırıp yenisini ekliyoruz. Daha önce eski isimlerle
-- kaydedilmiş satırlar varsa, onları da yeni isimlere çeviriyoruz ki kısıt hata vermesin.
update geri_bildirimler set durum = 'iyi' where durum = 'sakin';
update geri_bildirimler set durum = 'hafif' where durum = 'dikkatli';
update geri_bildirimler set durum = 'tehlikeli' where durum = 'riskli';

alter table geri_bildirimler drop constraint if exists geri_bildirimler_durum_check;
alter table geri_bildirimler add constraint geri_bildirimler_durum_check
  check (durum in ('carsaf', 'iyi', 'hafif', 'fazla', 'tehlikeli'));

-- Row Level Security'i açıyoruz (Supabase tablo oluşturunca otomatik açar ama garanti olsun)
alter table geri_bildirimler enable row level security;

-- Herkesin (giriş yapmamış ziyaretçiler dahil) okuyabilmesi için:
drop policy if exists "Herkes okuyabilir" on geri_bildirimler;
create policy "Herkes okuyabilir"
on geri_bildirimler for select
to anon
using (true);

-- Herkesin yeni bildirim ekleyebilmesi için:
drop policy if exists "Herkes ekleyebilir" on geri_bildirimler;
create policy "Herkes ekleyebilir"
on geri_bildirimler for insert
to anon
with check (true);

-- Not: genel update/delete politikası BİLEREK eklenmedi.
-- Yani hiç kimse (anon kullanıcılar) var olan bir bildirimin durumunu veya not metnini değiştiremez/silemez.
-- "Faydalı" oylaması için aşağıda SADECE sayacı artıran, güvenli bir fonksiyon tanımlanıyor —
-- bu fonksiyon dışında satıra dokunmanın bir yolu yok.

create or replace function faydali_isaretle(bildirim_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update geri_bildirimler
  set faydali_sayisi = faydali_sayisi + 1
  where id = bildirim_id;
$$;

grant execute on function faydali_isaretle(bigint) to anon;

-- Performans için indeks (konum bazlı sorgular hızlansın):
create index if not exists idx_geri_bildirimler_lat_lon on geri_bildirimler (lat, lon);
create index if not exists idx_geri_bildirimler_created_at on geri_bildirimler (created_at desc);

-- === Paylaşımlı favori/popüler noktalar ===
-- Herkesin görebileceği, herkesin ekleyebileceği favori deniz noktaları listesi.
-- Kişisel (sadece kullanıcının kendi tarayıcısında) değil, ortak bir liste.
create table if not exists favori_noktalar (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  lat float8 not null,
  lon float8 not null,
  ad text,
  ekleyen text
);

alter table favori_noktalar enable row level security;

drop policy if exists "Herkes favorileri okuyabilir" on favori_noktalar;
create policy "Herkes favorileri okuyabilir"
on favori_noktalar for select
to anon
using (true);

drop policy if exists "Herkes favori ekleyebilir" on favori_noktalar;
create policy "Herkes favori ekleyebilir"
on favori_noktalar for insert
to anon
with check (true);

create index if not exists idx_favori_noktalar_lat_lon on favori_noktalar (lat, lon);

-- === Site hakkında geri bildirim (deniz durumuyla ilgisiz, ayrı) ===
-- Bu, kullanıcıların "deniz nasıl" demesinden tamamen farklı — uygulamanın kendisi
-- hakkında (doğru çalışıyor mu, neyi beğendiler/beğenmediler gibi) yorum bırakabilecekleri
-- ayrı bir tablo. Haritada GÖSTERİLMEZ, sadece geliştirme amaçlı toplanır.
create table if not exists site_geri_bildirim (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  puan int check (puan between 1 and 5),
  mesaj text,
  kullanici_adi text
);

alter table site_geri_bildirim enable row level security;

drop policy if exists "Herkes site geri bildirimi ekleyebilir" on site_geri_bildirim;
create policy "Herkes site geri bildirimi ekleyebilir"
on site_geri_bildirim for insert
to anon
with check (true);

-- YENİ: Kullanıcılar sayfanın altında diğerlerinin yorumlarını görebilsin.
drop policy if exists "Herkes site yorumlarını okuyabilir" on site_geri_bildirim;
create policy "Herkes site yorumlarını okuyabilir"
on site_geri_bildirim for select
to anon
using (true);

-- Not: BİLEREK okuma (select) izni verilmedi — bu geri bildirimler herkese açık
-- gösterilmiyor, sadece toplanıyor. İstersen ileride Supabase Table Editor'dan
-- kendin görüntüleyebilirsin (proje sahibi olarak zaten erişimin var).

-- === Fotoğraflı yorumlar ===
-- Kullanıcılar deniz durumu yorumuna isteğe bağlı bir fotoğraf ekleyebilir.
alter table geri_bildirimler add column if not exists foto_url text;

-- Fotoğrafların yükleneceği, herkese açık okunabilir bir Storage bucket'ı.
-- (storage.buckets normal bir tablo olduğu için buraya SQL ile de eklenebiliyor,
-- Dashboard > Storage'dan elle oluşturmana gerek yok.)
insert into storage.buckets (id, name, public)
values ('yorum-fotolari', 'yorum-fotolari', true)
on conflict (id) do nothing;

-- Herkes (anon) bu bucket'a fotoğraf yükleyebilsin — ama SADECE ekleyebilir, diğer
-- tablolardaki aynı prensip: var olan bir fotoğrafı kimse değiştiremez/silemez.
drop policy if exists "Herkes yorum fotoğrafı yükleyebilir" on storage.objects;
create policy "Herkes yorum fotoğrafı yükleyebilir"
on storage.objects for insert
to anon
with check (bucket_id = 'yorum-fotolari');

-- Herkes fotoğrafları görebilsin (bucket zaten public ama garanti olsun):
drop policy if exists "Herkes yorum fotoğraflarını görebilir" on storage.objects;
create policy "Herkes yorum fotoğraflarını görebilir"
on storage.objects for select
to anon
using (bucket_id = 'yorum-fotolari');

-- === Şüpheli/uygunsuz yorum bildirme ===
-- Anon kullanıcıların bir yorumu (ve varsa fotoğrafını) doğrudan silme/değiştirme yetkisi
-- yok (bkz. yukarıdaki notlar) — bu yüzden "faydali_isaretle" ile AYNI güvenli desen: SADECE
-- sayacı artıran bir fonksiyon. Sayaç bir eşiği geçince istemci tarafında (index.html)
-- yorum soluklaştırılıyor / fotoğrafı gizleniyor — satırı gerçekten silmek istersen proje
-- sahibi olarak Supabase Table Editor'dan/Storage'dan kendin silebilirsin.
alter table geri_bildirimler add column if not exists sikayet_sayisi int not null default 0;

create or replace function sikayet_isaretle(bildirim_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update geri_bildirimler
  set sikayet_sayisi = sikayet_sayisi + 1
  where id = bildirim_id;
$$;

grant execute on function sikayet_isaretle(bigint) to anon;

